name: Scheduler test

on:
  schedule:
    - cron: "3 08 * * *"

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Scheduler fired
        run: echo "SCHEDULE FIRED at $(date -u)"
