name: Zvenigorod weather

on:
  workflow_dispatch:

jobs:
  weather:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      #- name: Install Russian CA certificates
      #  run: |
      #    sudo apt-get update
      #    sudo apt-get install -y ca-certificates
      #    sudo update-ca-certificates

      - name: Install Russian CA certificates
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates
          sudo curl -fsSL https://gu-st.ru/content/lending/russian_trusted_root_ca_pem.crt \
            -o /usr/local/share/ca-certificates/russian_trusted_root_ca.crt
          sudo curl -fsSL https://gu-st.ru/content/lending/russian_trusted_sub_ca_pem.crt \
            -o /usr/local/share/ca-certificates/russian_trusted_sub_ca.crt
          sudo update-ca-certificates

      - name: Check SSL certificates
        run: |
          python -c "import ssl; print(ssl.get_default_verify_paths())"
          python -c "import certifi; print(certifi.where())"
          curl -Iv https://platform-api2.max.ru/me

      - name: Run weather bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
          MAX_BOT_TOKEN: ${{ secrets.MAX_BOT_TOKEN }}
          MAX_CHAT_ID: ${{ secrets.MAX_CHAT_ID }}
        run: python app_zngrd_weather.py