name: Zvenigorod weather

on:
  workflow_dispatch:
  schedule:
    - cron: "20 * * * *"
      timezone: "Europe/Moscow"

jobs:
  weather:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run weather bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
        run: python app_zngrd_weather.py